### ISSUE TITLE
Updatefriendly way to change the gridsize

### ISSUE THREAD

**Issue by bohnmedia** [contao-bootstrap/grid#10]
Hello,

I changed the gridsize in bootstrap from 12 to 30.

I was able to change the gridsize in the extension by editing the "contao_bootstrap.yml". Is there also an updatefriendly way?

Thanks and
best regards,
Dennis

**Comment by dmolineus** [comment]
You can change it in the theme settings. No need to change any config file for it. :)

**Comment by bohnmedia** [comment]
Ups, sorry. 😄 

Thanks for this well done extension. This will help me a lot in future projects.

**Comment by dmolineus** [comment]
No problem. (I know the docs are missing....)
