### ISSUE TITLE
Overwrite or merge resets

### ISSUE THREAD

**Issue by bohnmedia** [contao-bootstrap/grid#12]
Hi,

yesterday I added a pull request for an additional feature to overwrite the resets.

Maybe its a little cleaner to merge them. You can only create one fork with an account so I made a clone for this idea.

https://github.com/bohnmedia/grid-alternate/commit/4fc85e1b3ffd00313f63552fb0a6e6b11d1ea4d5

Instead of the option "Overwrite resets" you have the option "Merge resets" here. This option uses only one div for all resets and also supports hiding, if you leave the checkbox blank on bigger sizes.

So this option

![image](https://user-images.githubusercontent.com/9419148/38305685-0a0e2dd0-380e-11e8-9496-d6aaa2ac0f27.png)

would result in that div.

![image](https://user-images.githubusercontent.com/9419148/38305749-4a4dd940-380e-11e8-85ac-c4bfab2d8cb5.png)

With the "overwriter" or "merger" that extension would be perfect for most of our projects. The extensions were changed updatefriendly, so an update shouldnt destroy existing layouts.

**Comment by dmolineus** [comment]
This feature will be implemented with (#29).
