### ISSUE TITLE
[Version 2.0.6] BS_Gallery_Grid kaputt

### ISSUE THREAD

**Issue by mj1985** [contao-bootstrap/grid#20]
Mit dem neuesten Update auf 2.0.6 ist die Bootstrap Gallery mit dem Template bs_gallery_default.html5 unbrauchbar.
Klassen aus dem Grid werden nicht mehr ausgegeben (nur noch "col" und "row", wobei letztere im Template steht) und somit stehen alle Bilder nebeneinander.

Nach dem Downgrade auf 2.0.5 funktioniert wieder alles. 
Fehlermeldungen gibt es nicht. Lediglich beim Dump auf 
`$this->grid` erhält man als Ergebnis `null`

**Comment by dmolineus** [comment]
Behoben mit 48494e296a581fb0234a98a30fb0439b6e5ac221 als Teil des hotfix/2.0.0 Branches. Release den Bugfix im Laufe der Woche.
