### ISSUE TITLE
must be of the type string

### ISSUE THREAD

**Issue by codesache** [contao-bootstrap/grid#25]
Hallo David,
ich erhalte folgende Fehlermeldung wenn ich ein Element "Sichtbarkeit - Umschlag Anfang/Ende" vom Catalog Manager in einen Artikel einsetze.

Type error: Argument 2 passed to ContaoBootstrap\Core\Listener\TemplateParseListener::parse() must be of the type string, null given, called in /Users/yyyyy/Documents/htdocs/yyyyy-c4/vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php on line 61

Lokal lauft Contao 4.4.35

contao-bootstrap/grid 2.0.8

PHP Version 7.2.8

Hast du eine Tipp für mich wo ich ansetzen kann?

Viele Grüße

Markus

**Comment by dmolineus** [comment]
Der Fehler tritt auf, wenn ein Template gerendert wird, dessen Templatename nicht gesetzt ist. Eine Möglichkeit wäre ein Element, dessen Objkt-Variable `$strTemplate` nicht gesetzt ist.
