### ISSUE TITLE
Feature: Add column name instead of grid name in grid separator

### ISSUE THREAD

**Issue by MDevster** [contao-bootstrap/grid#3]
It would be nice if you could also define a column name in the grid start element and the grid separator and if it could be displayed as follows. This makes it much clearer for the end user and he immediately knows where the element is placed.

before
![2017-08-23-feture-request-grid-org](https://user-images.githubusercontent.com/10244240/29605574-aab4b75a-87eb-11e7-83d1-187cafb95772.png)

afterwards
![2017-08-23-feture-request-grid](https://user-images.githubusercontent.com/10244240/29605616-d38b24b6-87eb-11e7-80c1-17ac0178750b.png)

**Comment by MDevster** [comment]
+1 custom title being set in the content elements
I think its better for multilanguage support and easier to implement.

**Comment by seibtph** [comment]
+1 for content element

**Comment by dmolineus** [comment]
Closed as nobody contributes nor funded this features so far. Feel free to open it again with a pull request
