### ISSUE TITLE
Wenn ein Modul & Ein Inhaltselement die selbe ID haben, überschreiben sich die Konfigurationen

### ISSUE THREAD

**Issue by Sioweb** [contao-bootstrap/grid#31]
Ich glaube das Problem liegt an dieser Zeile: https://github.com/contao-bootstrap/grid/blob/master/src/Component/Module/GridModule.php#L114 Hier sollte wohl statt `ce:` `mod:` stehen, kann das sein?

Jedenfalls nach dem Fix überschreibt sich die Konfigurationen nicht mehr, ich würde dir die SQL-Datei einfach senden, damit du es nachvollziehen kannst?

**Comment by dmolineus** [comment]
Ja, deine Fehleranalyse ist korrekt.

**Comment by dmolineus** [comment]
Fixed with 95c8aed55eb85e8d6763267f117b63335118a7d0
