### ISSUE TITLE
Keine Log-Files mehr

### ISSUE THREAD

**Issue by chriza** [contao-bootstrap/grid#32]
Contao 4.8.3
bootstrap/grid 2.1.1

Nach Installation der Extension werden Fehler nicht mehr in die Logfiles /var/logs/xxx.log geschrieben.

**Comment by dmolineus** [comment]
Ich wüsste nicht inwieweit die Erweiterung darauf Einfluss nehmen sollte. 

 - Um welche Fehler handelt es sich? Wo treten diese sonst auf?
 - Evtl. wird es durch eine Abhängigkeit ausgelöst?

**Comment by chriza** [comment]
Contao 4.8.4
bootstrap/grid 2.1.1

Ich habe eine frische neue Contao 4.8 Installation (noch ohne bootstrap) aufgesetzt, einen Startpunkt und eine Home-Seite mit einem p-Tag erstellt. Dazu habe ich eine scss Stylesheet Datei mit dem Inhalt: p { color: $red; } erstellt. Es wir in /var/logs eine Fehlerdatei erstellt. Diese Datei lösche ich.

Im zweiten Schritt installiere ich bootstrap/grid über den Contao Manager und ändere im Seitenlyout den Typ des Layouts auf Bootstrap.

Beim Reload der Home-Seite wird im FE die Contao Fehlerseite angezeigt, aber in /var/logs keine neue Fehlerdatei erzeugt.

**Comment by dmolineus** [comment]
Maybe caused of `catch` statement which catches all exceptions. Still wonder why the sass parsing is affected by it, but I gonna introduce a specific exception and only catch it.

https://github.com/contao-bootstrap/grid/search?q=catch&unscoped_q=catch

**Comment by chriza** [comment]
Es werden keine Log-Files angelegt, wenn ein Fehler an anderer Stelle auftritt. Z. B. bei einem fehlerhaften Template einer anderen Extension.

**Comment by dmolineus** [comment]
Fixed with 55f11cb009432335f0858fa33a12c00a92aa078c
