### ISSUE TITLE
ce_bs_grid_gallery alt und class kein Leerzeichen

### ISSUE THREAD

**Issue by codesache** [contao-bootstrap/grid#35]
Mir ist beim Einsatz einer ce_bs_grid_gallery mit 4 Spalten aufgelaffen, das im Quellcode am IMG TAG zwischen alt und class kein Leerzeichen ist. Der Firefox meckert mir das an.

Finde dazu keine Stelle im ce_bs_grid_gallery.html5 TPL deshalb die Vermutung es wird in der Erweiterung zusammen gesetzt.

**Comment by dmolineus** [comment]
Welche Version von `contao-bootstrap/grid` ist installiert? Das Image-Tag wird im picture-Template gerendert. Hier sollten dann wohl die Ursache liegen. Contao-bootstrap liefert allerdings kein angepasstes Picture-Template mit.

https://github.com/contao-bootstrap/grid/blob/92f687e6c6a82ca7118224617e096897faf0c2b8/src/Resources/contao/templates/gallery/bs_gallery_default.html5#L14

**Comment by codesache** [comment]
Version 2.1.1 mit Contao 4.8.5 > nach dem Update auf die 2.1.2 passt es jetzt.
Ticket kann geschlossen werden!
