### ISSUE TITLE
stacktrace beim composer update bzw install

### ISSUE THREAD

**Issue by srhinow** [contao-bootstrap/grid#36]
Contao4.8.7
php7.3
contao-bootstrap/bundle 2.1.1

folgende Meldungen kommen immer wenn ich nen Projekt mit composer update bzw composer install auf der commandline ausführe:
`PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/x/xxx/xxxxxx/contao4/vendor/contao-bootstrap/grid/src/Listener/ThemeImportListener.php on line 90
PHP Stack trace:
PHP   1. {main}() /var/www/x/xxx/xxxxxx/contao4/vendor/contao/manager-bundle/bin/contao-console:0
PHP   2. Contao\ManagerBundle\Console\ContaoApplication->run() /var/www/x/xxx/xxxxxx/contao4/vendor/contao/manager-bundle/bin/contao-console:38
PHP   3. Contao\ManagerBundle\Console\ContaoApplication->doRun() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/console/Application.php:149
PHP   4. Contao\ManagerBundle\Console\ContaoApplication->registerCommands() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/framework-bundle/Console/Application.php:65
PHP   5. Contao\ManagerBundle\HttpKernel\ContaoKernel->boot() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/framework-bundle/Console/Application.php:159
PHP   6. Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/http-kernel/Kernel.php:133
PHP   7. Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer() /var/www/x/xxx/xxxxxx/contao4/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php:318
PHP   8. Contao\ManagerBundle\HttpKernel\ContaoKernel->dumpContainer() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/http-kernel/Kernel.php:577
PHP   9. Symfony\Component\DependencyInjection\Dumper\PhpDumper->dump() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/http-kernel/Kernel.php:746
PHP  10. Symfony\Component\DependencyInjection\Dumper\PhpDumper->addServices() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:221
PHP  11. Symfony\Component\DependencyInjection\Dumper\PhpDumper->addService() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:880
PHP  12. Symfony\Component\DependencyInjection\Dumper\PhpDumper->addServiceInclude() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:722
PHP  13. Symfony\Component\DependencyInjection\Dumper\PhpDumper->collectLineage() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:470
PHP  14. Contao\ManagerPlugin\Config\ContainerBuilder->getReflectionClass() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:408
PHP  15. Symfony\Component\Config\Resource\ClassExistenceResource->isFresh() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/dependency-injection/ContainerBuilder.php:353
PHP  16. class_exists() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/config/Resource/ClassExistenceResource.php:78
PHP  17. spl_autoload_call() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/config/Resource/ClassExistenceResource.php:78
PHP  18. Composer\Autoload\ClassLoader->loadClass() /var/www/x/xxx/xxxxxx/contao4/vendor/symfony/config/Resource/ClassExistenceResource.php:78
PHP  19. Composer\Autoload\includeFile() /var/www/x/xxx/xxxxxx/contao4/vendor/composer/ClassLoader.php:322
`

**Comment by dmolineus** [comment]
Please update your packages. Issue got fixed in January 2019 with 67a361ddd472ffcad7ca023b5272d174ebf221ec#diff-6d6ab2b615defc2c6cad0e4f9cda3785.

**Comment by srhinow** [comment]
Hallo David, 
wat soll ich da denn noch updaten?
Ich habe vor nem Monat ne Neuinstallation mit Contao 4.8 gemacht und dann auch erst das bootstrap-bundle installiert. 

In meiner composer.json steht:
"contao-bootstrap/bundle": "^2.1",

Hab eben nochmal `composer update ` ausgeführt und es besteht weiterhin diese Meldung.

**Comment by dmolineus** [comment]
Gegenfrage: Was erwartest du, was ich noch machen soll neben den Bug zu fixen, zu releasen? Installieren musst du die aktuelle Version dann schon selber. Wenn diese bei dir nicht installiert wird, dann solltest du überprüfen warum.

1. Herausfinden, welche Version installiert ist `composer show contao-bootstrap/grid`
2. Herausfinden, welche Versionsabhängigkeiten die Aktualisierung verhindern.

Für solche Supportfragen bitte das Support-Kanäle der Contao Community (Slack, Forum, etc...) konsultieren

**Comment by srhinow** [comment]
Hallo David,
ich erwarte gar nichts. Ich bin nur leicht verwirrt da du (hier weiter oben im Issue) einerseits was mit 2.1.3 getaggt hast aber auch geschrieben hast, das es bereits seid Januar 2019 behoben sein soll.

Hier die Ausgabe:
```
composer show contao-bootstrap/grid
name     : contao-bootstrap/grid
descrip. : Bootstrap grid component
keywords : bootstrap, components, contao, grid
versions : * 2.0.4
type     : contao-bundle
license  : GNU Lesser General Public License v3.0 or later (LGPL-3.0-or-later) (OSI approved) https://spdx.org/licenses/LGPL-3.0-or-later.html#licenseText
source   : [git] https://github.com/contao-bootstrap/grid.git adc8a4c6027997f256410150228e779f91ea03bc
dist     : [zip] https://api.github.com/repos/contao-bootstrap/grid/zipball/adc8a4c6027997f256410150228e779f91ea03bc adc8a4c6027997f256410150228e779f91ea03bc
names    : contao-bootstrap/grid

autoload
psr-4
ContaoBootstrap\Grid\ => src/

requires
contao-bootstrap/core ^2.0
contao-community-alliance/meta-palettes ^2.0 || ^1.11
contao/core-bundle ^4.4
menatwork/contao-multicolumnwizard ^3.3.14
php >=7.1

requires (dev)
contao/manager-plugin ^2.0
php-http/guzzle6-adapter ^1.1
phpcq/all-tasks ^1.2

conflicts
netzmacht/contao-bootstrap *

```

Um rauszufinden warum es nicht die aktuelle Version installieren möchte habe ich diverse Erweiterungen aus der composer.json geschmissen. Unter anderem auch die contao-bootrap-bundle.
Wenn ich nun nur das grid-Paket via composer installieren möchte kommt folgende inkompatibilität-Meldung und bricht dort ab:
```

composer require contao-bootstrap/grid        :(
Using version ^2.2 for contao-bootstrap/grid
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install contao-bootstrap/grid 2.2.1
    - Installation request for menatwork/contao-multicolumnwizard (locked at 3.3.16) -> satisfiable by menatwork/contao-multicolumnwizard[3.3.16].
    - Conclusion: remove symfony/templating v5.0.2
    - Installation request for contao-bootstrap/grid ^2.2 -> satisfiable by contao-bootstrap/grid[2.2.0, 2.2.1].
    - Conclusion: don't install symfony/templating v5.0.2
    - contao-bootstrap/grid 2.2.0 requires symfony/templating ^3.3 || ^4.0 -> satisfiable by symfony/templating[v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, 
.......
```

hast du noch eine Idee was da schief läuft bzw was ich noch machen kann um die Ursache zu finden?

**Comment by srhinow** [comment]
Ich habe jetzt bis auf die Contao-bundles alle entfernt. Hier mal der Ausschnitt aus meiner composer.json

```
    "require": {
        "php": "^7.1",
        "ext-openssl": "*",
        "ext-zip": "*",
        "ext-json": "*",
        "contao/comments-bundle": "^4.8",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "^4.8",
        "contao/listing-bundle": "^4.8",
        "contao/manager-bundle": "4.8.*",
        "contao/news-bundle": "^4.8"
    },
    "minimum-stability": "beta",
```

auch wenn ich versuche die ältere Version 2.1 zu installieren kommt der Fehler mit dem symfony/templating

```
composer require contao-bootstrap/grid 2.1    :(
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for contao-bootstrap/grid 2.1 -> satisfiable by contao-bootstrap/grid[2.1.0].
    - Conclusion: remove symfony/templating v5.0.2
    - Conclusion: don't install symfony/templating v5.0.2
    - contao-bootstrap/grid 2.1.0 requires symfony/templating ^3.3 || ^4.0 -> satisfiable by symfony/templating[v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, 

```

**Comment by dmolineus** [comment]
Problem ist wohl, dass `symfony/templating ^5.0` installiert ist, was derzeit noch nicht von allen Bootstrap-Komponenten freigegeben wurde. Daher entscheidet sich Composer anscheinend die Grid-Komponente downzugraden anstatt `symfony/templating ^4.0` zu verwenden.

Mach folgendes:

```
composer require contao-bootstrap/grid 2.1 --no-update
composer update --no-dev -o
```

Bei einem einfachen `composer require` werden nicht alle Abhängigkeiten neu überprüft, daher scheitert der Befehl bei dir.

**Comment by srhinow** [comment]
Danke David das hat funktioniert.
