### ISSUE TITLE
In Contao 4.8.7 lässt sich das Modul nicht installieren

### ISSUE THREAD

**Issue by green-pixelbox** [contao-bootstrap/grid#37]
In Contao 4.8.7 lässt sich das Modul nicht über den Contao-Manager 1.2.2 installieren :(

**Comment by bohnmedia** [comment]
Ich konnte das Problem lösen, indem ich im Contao Manager die Erweiterung installiert und das Contao Bundle parallel aktualisiert habe.

**Comment by dmolineus** [comment]
Die Erweiterung läuft problemlos unter Contao 4.8.7 und lässt sich dort auch installieren. Bzgl. der Vorgehensweise folgende Links.

https://community.contao.org/de/showthread.php?76833-contao-bootstrap-grid-bricht-bei-Installation-ab&p=517301&viewfull=1#post517301
https://github.com/contao-bootstrap/tab/issues/8#issuecomment-565487041

Weitere Supportanfragen bitte im Forum stellen.
