### ISSUE TITLE
Internal Server Error beim kopieren/dublizieren von Formularfeldern

### ISSUE THREAD

**Issue by cmichael-de** [contao-bootstrap/grid#39]
Internal Server Error
Was ist das Problem?
Type error: Argument 1 passed to Netzmacht\Contao\Toolkit\Data\Model\ContaoRepository::find() must be of the type integer, string given, called in ***/vendor/contao-bootstrap/grid/src/Listener/Dca/FormFieldFixParentRelationListener.php on line 76

Error erscheint nach Klick auf einfügen des Formularfeldes (Formulargenerator) und auch beim "Speichern und Duplizieren" Button.

**Comment by dmolineus** [comment]
Fixed in 2.2.2
