### ISSUE TITLE
Error when copying files in filemanagement

### ISSUE THREAD

**Issue by Kahmoon** [contao-bootstrap/grid#40]
When i try to copy a file in Contao backend the following error appears

> Argument 2 passed to ContaoBootstrap\Grid\Listener\Dca\ParentFixContentParentRelationsListener::onCopy() must be an instance of Contao\DataContainer, string given, called in /homepages/46/xxx/htdocs/jagdbildungszentrum-v2/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Folder.php on line 881

Contao: 4.8.7
Bootstrap Grid: 2.2.2

https://community.contao.org/de/showthread.php?77044-Templates-Dateien-via-Dateiverwaltung-kopieren-erzeugt-Fehler&p=518770#post518770

**Comment by dmolineus** [comment]
Fixed with 2.2.3.
