### ISSUE TITLE
Bootstrap gallery creates no pagiantion

### ISSUE THREAD

**Issue by Kahmoon** [contao-bootstrap/grid#42]
Default template has no output for pagination

Contao 4.9.2
Bootstrap für Contao Core 2.0.3

Edit: Output also does not stop at maximum images per page.

See https://community.contao.org/de/showthread.php?77852-Bootstrap-Galerie-erzeugt-keine-Paginierung&p=524420

VG
Frank

**Comment by Kahmoon** [comment]
Is there a hotfix or workaround meanwhile to 2.2.4?

**Comment by dmolineus** [comment]
I cannot confirm this issue. It works in my test case. Do you use the random sorting? Then the pagination is disabled, as it also is in Contao.

**Comment by Kahmoon** [comment]
Oh!! Yes, its random sorting but i don t see a reason why pagination should be disabled die to this setting?!

**Comment by dmolineus** [comment]
If you use a random sorting you can't garantee that you see images multiple times. The random order isn't cached but created on each request.
