### ISSUE TITLE
Package not compatible with current (managed) Contao 4.11.5 (with Symfony 5 framework)

### ISSUE THREAD

**Issue by Baloobear** [contao-bootstrap/grid#45]
Hello,

unfortunately your package is not installable with a currently fresh installation of the managed version of Contao (v4.11.5 with Symfony 5 framework).

```
$ composer require contao-bootstrap/grid
Using version ^2.3 for contao-bootstrap/grid
./composer.json has been updated
Running composer update contao-bootstrap/grid
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - contao-bootstrap/grid[2.3.0, ..., 2.3.1] require symfony/config ^3.3 || ^4.0 -> found symfony/config[v3.3.0, ..., v3.4.47, v4.0.0, ..., v4.4.27] but the package is fixed to v5.2.10 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires contao-bootstrap/grid ^2.3 -> satisfiable by contao-bootstrap/grid[2.3.0, 2.3.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Maybe you can update your requirements to include the Symfony 5 framework?

Thanks.

Kind Regards,
Dennis

**Comment by Ernestopheles** [comment]
Having a similar issue trying to uograde from Contao 4.12 to 4.13 (till 4.12.6 bootstrap is running fine inmy installation...).

Conflict:  bootstrap requires symfony/dependency-injection: ^3.4.26 || ^4.1.12 with  contao/calendar-bundle 4.13.0 requires symfony/dependency-injection ^5.4.

Kindly asking for an update of requirements.
 Thanks a lot, best regards, ernst

**Comment by dmolineus** [comment]
`contao-bootstrap/grid ^2.4@dev` is compatible with Contao 4.13 and Symfony 5.

**Comment by dmolineus** [comment]
> Thanks for information. Does this help me in any way to update to
contao 4.13 having the MATE theme installed?

I don't know. Please contact the developer of the MATE theme for any support of it. I'm not part of the theme nor the developer contributed anything to contao-bootstrap.
