### ISSUE TITLE
Fehlendes "^" in composer.json für Bundle "symfony/dependency-injection"

### ISSUE THREAD

**Issue by mwitzmann** [contao-bootstrap/grid#50]
Bei Verwendung des Bundles "contao-bootstrap/grid" in Version 2.4.0 ein Update von Contao 4.9.27 auf 4.9.28 wird "symfony/dependency-injection" in Version 4.4.0 installiert, es müsste jedoch 4.4.40 sein.
In der composer.json fehlt vermutlich "^" vor 4.4:
https://github.com/contao-bootstrap/grid/blob/2.4.0/composer.json

**Comment by dmolineus** [comment]
Fixed in 2.4.1
