### ISSUE TITLE
Zugriffsschutz vererben

### ISSUE THREAD

**Issue by swinde** [contao-bootstrap/grid#7]
wäre es programmiertechnisch möglich, den Zugriffsschutz vom Grid Startelement an Seperatoren und Stop Element automatisch zu vererben?

**Comment by dmolineus** [comment]
Möglich schon. Nur ob es der Aufrand sich rechnet. Man muss dann ja höchstwahrscheinlich auch die Inhalte innerhalt dem Grid den Zugriffsschutz setzen. Und über mehrere bearbeiten ist ja kein großer Akt.

**Comment by swinde** [comment]
>Und über mehrere bearbeiten ist ja kein großer Akt.
Stimmt. Daran hatte ich in dem Moment gar nicht gedacht!
