### ISSUE TITLE
Fehlermeldung im Formular-Grid

### ISSUE THREAD

**Issue by cboelter** [contao-bootstrap/grid#9]
Wenn ich die Grids im Formular-Generator konfigurieren möchte erhalte ich folgende Fehlermeldung:

```Symfony\Component\Debug\Exception\ClassNotFoundException:
Attempted to load class "GridModel" from the global namespace.
Did you forget a "use" statement for "ContaoBootstrap\Grid\Model\GridModel"?

  at vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:621
  at Contao\Model->getRelated('bs_grid')
     (vendor/contao-bootstrap/grid/src/Listener/Dca/FormListener.php:162)
  at ContaoBootstrap\Grid\Listener\Dca\FormListener->getGridParentOptions(object(DC_Table))
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:1354)```

**Comment by dmolineus** [comment]
This line has to be fixed to tl_bs_grid.title I guess. I don't know why this error did not occur in my projects so far. ;-)

https://github.com/contao-bootstrap/grid/blob/master/src/Resources/contao/dca/tl_form_field.php#L61

**Comment by dmolineus** [comment]
Commit f27d7e2 sollte das Problem beheben. Wäre super, wenn du bestätigen kannst, dass der Fehler nicht mehr auftritt. Seltsamerweise habe ich den Fehler nicht. Bugfix befindet sich im Branch dev-hotfix/2.0-2.

**Comment by dmolineus** [comment]
Just released the version 2.0.2.
